version: "3.7"

services:
  mysql:
    platform: linux/amd64
    container_name: mysql-saferpayofficial-16
    image: mysql:5.7
    ports:
      - "9002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    restart: always
    healthcheck:
      test: "mysqladmin ping -h127.0.0.1 -uroot -pprestashop --silent"
      interval: 10s
    networks:
      - prestashop_saferpayofficial_net_16

  prestashop-16:
    platform: linux/amd64
    container_name: prestashop-saferpayofficial-16
    build:
      context: .
      dockerfile: .docker/Dockerfile.16
    environment:
      PS_INSTALL_AUTO: 1
      PS_ENABLE_SSL: 1
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      DB_SERVER: mysql
      PS_DOMAIN: saferpayofficial16debug.ngrok.io
      PS_FOLDER_INSTALL: install
      PS_FOLDER_ADMIN: admin1
    depends_on:
      - mysql
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www/html/modules/saferpayofficial
    networks:
      - prestashop_saferpayofficial_net_16
    healthcheck:
      test: "curl -f localhost:8002"
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - '6969:8080'
    networks:
      - prestashop_saferpayofficial_net_16

  mailhog:
    image: mailhog/mailhog
    container_name: saferpayofficial_mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  prestashop_saferpayofficial_net_16:
    name: 'prestashop_saferpayofficial_net_16'
