describe('Admin journey - part 1', () => {
  it('1 - Configure plugin credentials', () => {
    cy.viewport(1920,1080)
    cy.visit('/admin1/')
    cy.get('#email').type('demo@demo.com')
    cy.get('#passwd').type('demodemo')
    cy.get('#submit_login').click()
    cy.wait(1000)
    cy.visit('/admin1/index.php?controller=AdminWorldlineopConfiguration')
    cy.contains('I understand').click()
    cy.get('[name="worldlineopAccountSettings[testPspid]"]')
    cy.get('[name="worldlineopAccountSettings[testApiKey]"]')
    cy.get('[name="worldlineopAccountSettings[testApiSecret]"]')
    cy.get('[name="worldlineopAccountSettings[testWebhooksKey]"]')
    cy.get('[name="worldlineopAccountSettings[testWebhooksSecret]"]')
    cy.get('[name="submitTestCredentialsForm"]').click()
    cy.contains('Account credentials are valid. Account settings saved successfully.').should('be.visible')
  })
})