services:
    Invertus\SaferPay\Repository\SaferPayLogoRepository:
        class: Invertus\SaferPay\Repository\SaferPayLogoRepository

    Invertus\SaferPay\Repository\SaferPayOrderRepository:
        class: Invertus\SaferPay\Repository\SaferPayOrderRepository

    Invertus\SaferPay\Repository\SaferPayPaymentRepository:
        class: Invertus\SaferPay\Repository\SaferPayPaymentRepository

    Invertus\SaferPay\Repository\SaferPayRestrictionRepository:
        class: Invertus\SaferPay\Repository\SaferPayRestrictionRepository

    Invertus\SaferPay\Repository\SaferPayCardAliasRepository:
        class: Invertus\SaferPay\Repository\SaferPayCardAliasRepository

    Invertus\SaferPay\Repository\SaferPaySavedCreditCardRepository:
        class: Invertus\SaferPay\Repository\SaferPaySavedCreditCardRepository

    Invertus\SaferPay\Repository\SaferPayFieldRepository:
        class: Invertus\SaferPay\Repository\SaferPayFieldRepository

    Invertus\SaferPay\Repository\OrderRepository:
        class: Invertus\SaferPay\Repository\OrderRepository