name: CI/CD pipeline

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      # Change these values depending on project.
      ps-module-name: saferpayofficial
      project-workspace-dir: ${{ github.workspace }}/../workspace
    strategy:
      matrix:
        PS: [ 1.7.8-7.1 ]
        testsuite: [ lint, phpstan, unit, integration ]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Swap Space
        uses: Invertus/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Set up workspace
        shell: bash
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.PS_MODULE_WORKSPACE_SAFERPAY_PRIVATE_KEY }}"
          git clone git@github.com:Invertus/ps-module-workspace.git ${{ env.project-workspace-dir }}
          cd ${{ env.project-workspace-dir }}
          sed 's/PROJECT_NAME=.*/PROJECT_NAME=${{ env.ps-module-name }}/g' < .env.dist |
          sed 's/PS_VERSION_TAG=.*/PS_VERSION_TAG=${{ matrix.PS }}/g' > .env
          make create-modules-dir
          cp -R ${{ github.workspace }} ${{ env.project-workspace-dir }}/prestashop/${{ matrix.PS }}/modules/${{ env.ps-module-name }}

      - name: Run PrestaShop
        run: |
          (cd ${{ env.project-workspace-dir }} && docker compose up -d)

      - name: Healthcheck
        run: |
          timeout 120s sh -c 'until docker ps | grep ${{ env.ps-module-name }}-ps-prestashop-${{ matrix.PS }} | grep -q "(healthy)"; do echo "Waiting for container to be healthy..."; sleep 1; done'

      - name: Cache composer folder
        uses: actions/cache@v3
        with:
          path: ${{ env.project-workspace-dir }}/prestashop/${{ matrix.PS }}/modules/${{ env.ps-module-name }}/vendor
          key: ${{ github.sha }}

      - name: Install module
        run: docker exec -i ${{ env.ps-module-name }}-ps-prestashop-${{ matrix.PS }} bash -c "cd /var/www/html && php bin/console prestashop:module install ${{ env.ps-module-name }}"

      - name: Run ${{ matrix.testsuite }} tests
        run: docker exec -i ${{ env.ps-module-name }}-ps-prestashop-${{ matrix.PS }} bash -c "cd /var/www/html/modules/${{ env.ps-module-name }} && make ci-${{ matrix.testsuite }} ps_version_tag=${{ matrix.PS }}"

  deploy-dev:
    name: Deploy to dev environment
    if: github.event_name == 'push' && (contains(github.ref, 'refs/heads/main'))
    needs: [ test ]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INVERTUSDEMO_APACHE_SERVER_IP }}
          username: ${{ secrets.INVERTUSDEMO_APACHE_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_FOR_INVERTUSDEMO_AUTH }}
          script: (cd ${{ secrets.WORKSPACE_DIR }} && make demo-deploy)
          debug: true

  prepare-zip:
    name: Prepare module ZIP artifact
    runs-on: ubuntu-latest
    needs: [ test ]
    env:
      MODULE_NAME: saferpayofficial
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build module ZIP
        run: |
          composer dump-autoload --no-dev --optimize --classmap-authoritative
          cp .github/.htaccess vendor/.htaccess
          rm -rf .git .github tests .php-cs-fixer.php Makefile cypress* docker-compose*.yml package.json package-lock.json .docker vendor-bin vendor/hambug update_installed_json.php
          mkdir ${{ env.MODULE_NAME }}
          rsync -Rr ./ ./${{ env.MODULE_NAME }}
          chmod -R 777 ${{ env.MODULE_NAME }}/var/cache
          shopt -s extglob
          rm -r !(${{ env.MODULE_NAME }})
          find . -maxdepth 1 -type f -exec rm "{}" \;
          cd ${{ env.MODULE_NAME }} && rm -rf ${{ env.MODULE_NAME }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: ${{ env.MODULE_NAME }}
          path: ./