# This is a basic workflow that is manually triggered

name: Cypress E2E Automation
on: [ pull_request ]

jobs:
  Cypress-E2E-automation:
    runs-on: ubuntu-latest
    strategy:
     fail-fast: false
     matrix:
       containers: [1,2,3,4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0

      - name: Configuring the ecommerce and running the E2E tests
        run: |
          export CYPRESS_BRASA_ADMIN_URL='${{ secrets.BRASA_ADMIN_URL }}'
          export CYPRESS_BRASA_EMAIL='${{ secrets.BRASA_EMAIL }}'
          export CYPRESS_BRASA_PASSWORD='${{ secrets.BRASA_PASSWORD }}'

      - name: Cypress Cloud GitHub
        uses: cypress-io/github-action@v6
        with:
         record: true
         parallel: true
         group: 'Saferpay E2E'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}cy.contains('a','Home').should('have.attr', 'href', '/home')


      - name: Archive videos and screenshots after the E2E test running
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Cypress_Saferpay_videos_screenshots
          retention-days: 2
          path: |
            cypress/videos
            cypress/screenshots
